services:
  db:
    image: mysql:8
    container_name: tracey_mysql
    restart: always
    volumes:
      - data:/var/lib/mysql
      - /opt/mysql/mysql_data:/var/lib/mysql
      - /tmp/mysql/mysqld:/var/run/mysqld
    environment:
      - MYSQL_HOST=localhost
      - MYSQL_PORT=3306
      - MYSQL_ROOT_PASSWORD=tracey
      - MYSQL_DATABASE=tracey
      - MYSQL_USER=tracey
      - MYSQL_PASSWORD=tracey
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysql", "-h", "localhost", "-u", "root", "-p tracey", "-e", "SELECT 1"]
      timeout: 20s
      retries: 10

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tracey_backend
    command: /bin/bash -c "python manage.py runserver 0.0.0.0:8000"
    restart: always
    volumes:
      - .:/app
      - /tmp/mysql/mysqld:/run/mysqld
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
        #condition: service_healthy

volumes:
  data:
