motifsNames = ['Ha.I', 'Ha.II', 'Ha.III', 'Ha.IV', 'Hb.I', 'Hb.II', 'Hb.III', 'Hc.I', 'Hc.III',
			  'Ha.I.Syx18', 'Ha.I.Ufe1', 'Ha.III.a', 'Ha.III.b', 'Ha.IV.Sso', 'Ha.IV.Syx',
			  'Hb.II.Bos1', 'Hb.II.Gos1', 'Hb.II.Membrin', 'Hb.III.b', 'Hb.III.d',
			  'Hc.III.b', 'Hc.III.c',
			  'Qa.I', 'Qa.II', 'Qa.III', 'Qa.IV', 'Qb.I', 'Qb.II', 'Qb.III', 'Qc.I', 'Qc.II', 'Qc.III', 'R.I',
			  'R.II', 'R.III', 'R.IV', 'R.Reg', 'SNAP',
			  'Qa.I.Syx18', 'Qa.I.Ufe1', 'Qa.II.Sed5', 'Qa.II.Syx5', 'Qa.III.a', 'Qa.III.b',
			  'Qa.IV.Sso', 'Qa.IV.Syx', 'Qb.II.Bos1', 'Qb.II.Gos1', 'Qb.II.Membrin',
			  'Qb.III.b', 'Qb.III.d', 'Qc.III.b', 'Qc.III.c', 'SNAPb', 'SNAPc'
			  ]
HabcSNAREMotifsNames = ['SNAREa.I', 'SNAREa.II', 'SNAREa.III', 'SNAREa.IV', 'SNAREb.I', 'SNAREb.II', 'SNAREb.III', 'SNAREc.I', 'SNAREc.III',
						'SNAREa.I.Syx18', 'SNAREa.I.Ufe1', 'SNAREa.II.Sed5', 'SNAREa.II.Syx5',
						'SNAREa.III.a', 'SNAREa.III.b', 'SNAREa.IV.Sso', 'SNAREa.IV.Syx',
						'SNAREb.II.Bos1', 'SNAREb.II.Gos1', 'SNAREb.II.Membrin', 'SNAREb.III.b',
						'SNAREb.III.d', 'SNAREc.III.b', 'SNAREc.III.c'
						]
allMotifsNames = ['Ha.I', 'Ha.II', 'Ha.III', 'Ha.IV', 'Hb.I', 'Hb.II', 'Hb.III', 'Hc.I', 'Hc.III',
				  'Ha.I.Syx18', 'Ha.I.Ufe1', 'Ha.III.a', 'Ha.III.b', 'Ha.IV.Sso', 'Ha.IV.Syx',
				  'Hb.II.Bos1', 'Hb.II.Gos1', 'Hb.II.Membrin', 'Hb.III.b', 'Hb.III.d',
				  'Hc.III.b', 'Hc.III.c',
				  'Qa.I', 'Qa.II', 'Qa.III', 'Qa.IV', 'Qb.I', 'Qb.II', 'Qb.III', 'Qc.I', 'Qc.II', 'Qc.III', 'R.I',
				  'R.II', 'R.III', 'R.IV', 'R.Reg', 'SNAP',
				  'Qa.I.Syx18', 'Qa.I.Ufe1', 'Qa.II.Sed5', 'Qa.II.Syx5', 'Qa.III.a', 'Qa.III.b',
				  'Qa.IV.Sso', 'Qa.IV.Syx', 'Qb.II.Bos1', 'Qb.II.Gos1', 'Qb.II.Membrin',
				  'Qb.III.b', 'Qb.III.d', 'Qc.III.b', 'Qc.III.c', 'SNAPb', 'SNAPc',
				  'SNAREa.I', 'SNAREa.II', 'SNAREa.III', 'SNAREa.IV', 'SNAREb.I', 'SNAREb.II', 'SNAREb.III', 'SNAREc.I', 'SNAREc.III',
				  'SNAREa.I.Syx18', 'SNAREa.I.Ufe1', 'SNAREa.II.Sed5', 'SNAREa.II.Syx5',
				  'SNAREa.III.a', 'SNAREa.III.b', 'SNAREa.IV.Sso', 'SNAREa.IV.Syx',
				  'SNAREb.II.Bos1', 'SNAREb.II.Gos1', 'SNAREb.II.Membrin', 'SNAREb.III.b',
				  'SNAREb.III.d', 'SNAREc.III.b', 'SNAREc.III.c'
				  ]
subTree = {'Ha.I': ['Ha.I.Syx18', 'Ha.I.Ufe1'],
		   'Ha.II': '',
		   'Ha.III': ['Ha.III.a', 'Ha.III.b'],
		   'Ha.IV': ['Ha.IV.Sso', 'Ha.IV.Syx'],
		   'Hb.I': '',
		   'Hb.II': ['Hb.II.Bos1', 'Hb.II.Gos1', 'Hb.II.Membrin'],
		   'Hb.III': ['Hb.III.b', 'Hb.III.d'],
		   'Hc.I': '',
		   'Hc.III': ['Hc.III.b', 'Hc.III.c'],
		   'Qa.I': ['Qa.I.Syx18', 'Qa.I.Ufe1'],
		   'Qa.II': ['Qa.II.Sed5', 'Qa.II.Syx5'],
		   'Qa.III': ['Qa.III.a', 'Qa.III.b'],
		   'Qa.IV': ['Qa.IV.Sso', 'Qa.IV.Syx'],
		   'Qb.I': '',
		   'Qb.II': ['Qb.II.Bos1', 'Qb.II.Gos1', 'Qb.II.Membrin'],
		   'Qb.III': ['Qb.III.b', 'Qb.III.d'],
		   'Qc.I': '',
		   'Qc.II': '',
		   'Qc.III': ['Qc.III.b', 'Qc.III.c'],
		   'R.I': '',
		   'R.II': '',
		   'R.III': '',
		   'R.IV': '',
		   'R.Reg': '',
		   'SNAP': ['SNAPb', 'SNAPc'],
		   'SNAREa.I': ['SNAREa.I.Syx18', 'SNAREa.I.Ufe1', 'SNAREa.II.Sed5', 'SNAREa.II.Syx5', 'SNAREa.III.a', 'SNAREa.III.b', 'SNAREa.IV.Sso', 'SNAREa.IV.Syx'],
		   'SNAREa.II': ['SNAREa.II.Sed5', 'SNAREa.II.Syx5', 'SNAREa.III.a', 'SNAREa.III.b'],
		   'SNAREa.III': ['SNAREa.III.a', 'SNAREa.III.b'],
		   'SNAREa.IV': ['SNAREa.IV.Sso', 'SNAREa.IV.Syx'],
		   'SNAREb.I': ['SNAREb.II.Bos1', 'SNAREb.II.Gos1', 'SNAREb.II.Membrin', 'SNAREb.III.b', 'SNAREb.III.d'],
		   'SNAREb.II': ['SNAREb.II.Bos1', 'SNAREb.II.Gos1', 'SNAREb.II.Membrin', 'SNAREb.III.b', 'SNAREb.III.d'],
		   'SNAREb.III': ['SNAREb.III.b', 'SNAREb.III.d'],
		   'SNAREc.I': ['SNAREc.III.b', 'SNAREc.III.c'],
		   'SNAREc.III': ['SNAREc.III.b', 'SNAREc.III.c']
		   }

## TRACEY
tracey_motifsNames = ['Ha.I', 'Ha.II', 'Ha.III', 'Ha.IV', 'Hb.I', 'Hb.II', 'Hb.III', 'Hc.I', 'Hc.III',
					  'Ha.III.Ha.III.a', 'Ha.III.Ha.III.b', 'Ha.IV.Sso.IV', 'Ha.IV.Syx.IV',
					  'Hb.II.Hb.II.a', 'Hb.II.Hb.II.b',
					  'Hc.III.Hc.III.b', 'Hc.III.Hc.III.c',
					  'Qa.I', 'Qa.II', 'Qa.III', 'Qa.IV', 'Qb.I', 'Qb.II', 'Qb.III', 'Qc.I', 'Qc.II', 'Qc.III',
					  'R.I', 'R.II', 'R.III', 'R.IV', 'R.Reg',
					  'Qa.III.Qa.III.a', 'Qa.III.Qa.III.b', 'Qb.III.Qb.III.b', 'Qb.III.Qb.III.d',
					  'Qc.III.Qc.III.b', 'Qc.III.Qc.III.c', 'SNAPb', 'SNAPc']
tracey_subTree = {'Ha.I': '',
				  'Ha.II': '',
				  'Ha.III': ['Ha.III.Ha.III.a', 'Ha.III.Ha.III.b'],
				  'Ha.IV': ['Ha.IV.Sso.IV', 'Ha.IV.Syx.IV'],
				  'Hb.I': '',
				  'Hb.II': ['Hb.II.Hb.II.a', 'Hb.II.Hb.II.b',],
				  'Hb.III': '',
				  'Hc.I': '',
				  'Hc.III': ['Hc.III.Hc.III.b', 'Hc.III.Hc.III.c',],
				  'Qa.I': '',
				  'Qa.II': '',
				  'Qa.III': ['Qa.III.Qa.III.a', 'Qa.III.Qa.III.b'],
				  'Qa.IV': '',
				  'Qb.I': '',
				  'Qb.II': '',
				  'Qb.III': ['Qb.III.Qb.III.b', 'Qb.III.Qb.III.d'],
				  'Qc.I': '',
				  'Qc.II': '',
				  'Qc.III': ['Qc.III.Qc.III.b', 'Qc.III.Qc.III.c'],
				  'R.I': '',
				  'R.II': '',
				  'R.III': '',
				  'R.IV': '',
				  'R.Reg': '',
				  'SNAP': ['SNAPb', 'SNAPc']
				  }


