"""
Django settings for traceyDB project.

Generated by 'django-admin startproject' using Django 3.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""
import os, environ
from pathlib import Path
import mimetypes

mimetypes.add_type("text/css", ".css", True)

env = environ.Env(
    # set casting, default value
    DEBUG=(bool, True)
)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
CORE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Take environment variables from .env file
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env('DEBUG')

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'

# Production hardening — only applied when DEBUG is off. Each flag is env-driven
# so it can be rolled out gradually and rolled back without a code change.
if not DEBUG:
    # Safe defaults for an HTTPS-only site:
    SESSION_COOKIE_SECURE = env.bool('SESSION_COOKIE_SECURE', default=True)
    CSRF_COOKIE_SECURE = env.bool('CSRF_COOKIE_SECURE', default=True)
    # Off by default: enable only after confirming Apache forwards
    # "X-Forwarded-Proto: https" (otherwise this causes a redirect loop).
    SECURE_SSL_REDIRECT = env.bool('SECURE_SSL_REDIRECT', default=False)
    # Start at 0. Raise to 3600, then 2592000, then 31536000 once you are
    # sure every subdomain is HTTPS — HSTS is hard to undo in browsers.
    SECURE_HSTS_SECONDS = env.int('SECURE_HSTS_SECONDS', default=0)
    SECURE_HSTS_INCLUDE_SUBDOMAINS = env.bool('SECURE_HSTS_INCLUDE_SUBDOMAINS', default=False)
    SECURE_HSTS_PRELOAD = env.bool('SECURE_HSTS_PRELOAD', default=False)

# Assets Management
ASSETS_ROOT = os.getenv('ASSETS_ROOT', '/static/assets')

ALLOWED_HOSTS        = ['dcsrs-tracey.ad.unil.ch', 'tracey.unil.ch', 'localhost', '127.0.0.1', env('SERVER', default='127.0.0.1') ]
CSRF_TRUSTED_ORIGINS = ['http://localhost:85', 'http://127.0.0.1', 'https://' + env('SERVER', default='127.0.0.1') ]

# Captcha options
CAPTCHA_CHALLENGE_FUNCT = 'captcha.helpers.math_challenge' # default: 'captcha.helpers.random_char_challenge'
CAPTCHA_LETTER_ROTATION = (-20, 20)
CAPTCHA_NOISE_FUNCTIONS = ('captcha.helpers.noise_arcs','captcha.helpers.noise_dots',)
CAPTCHA_FONT_SIZE = 30
#CAPTCHA_2X_IMAGE = True # this makes the image slightly more readable on e.g. HiDPI screens, but could also make the CAPTCHA potentially easier to break by a bot.

# example of function for captcha
# def random_digit_challenge():
#     ret = u''
#     for i in range(6):
#         ret += str(random.randint(0,9))
#     return ret, ret


# Max GET/POST fields
DATA_UPLOAD_MAX_NUMBER_FIELDS = 20000

# Application definition
INSTALLED_APPS = [
    'apps.config.AppsConfig',
    'captcha',
    'django_extensions',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sitemaps',
    'django_htmx',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # Serves collected static files directly from gunicorn (compressed, cached).
    # Apache still handles /static/ in production if configured to; this is a
    # safety net so static never depends on the web-server config being perfect.
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_htmx.middleware.HtmxMiddleware',
    'csp.middleware.CSPMiddleware',
    'django_permissions_policy.PermissionsPolicyMiddleware',
]

ROOT_URLCONF = 'core.urls'
LOGIN_REDIRECT_URL = "home"  # Route defined in home/urls.py
LOGOUT_REDIRECT_URL = "home"  # Route defined in home/urls.py
TEMPLATE_DIR = os.path.join(CORE_DIR, "apps/templates")  # ROOT dir for templates

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [TEMPLATE_DIR],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'apps.context_processors.cfg_assets_root',
            ],
            'libraries':{
                'template_filters': 'apps.templatetags.template_filters',
            },
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': env('DB_NAME'),
        'USER': env('DB_USER'),
        'PASSWORD': env('DB_PASSWORD'),
        'HOST': env('DB_HOST', default='localhost'),
        'PORT': env('DB_PORT', default='3306'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 8,
        }
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Europe/Zurich'

USE_I18N = True

# USE_L10N was removed in Django 5.0 — localized formatting is always on.

USE_TZ = True


#############################################################
# SRC: https://devcenter.heroku.com/articles/django-assets

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.9/howto/static-files/
STATIC_ROOT = os.path.join(CORE_DIR, 'staticfiles')
STATIC_URL = '/static/'

# Extra places for collectstatic to find static files.
STATICFILES_DIRS = (
    os.path.join(CORE_DIR, 'apps/static'),
)

# WhiteNoise: compress collected static files and serve them with far-future
# cache headers. CompressedStaticFilesStorage (no "Manifest") is used on purpose
# — this template references some assets that would break manifest hashing.
STORAGES = {
    "default": {"BACKEND": "django.core.files.storage.FileSystemStorage"},
    "staticfiles": {"BACKEND": "whitenoise.storage.CompressedStaticFilesStorage"},
}


#############################################################
#############################################################

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


#############################################################

# Content Security Policy (django-csp 4.x — the flat CSP_* settings were removed
# in 4.0). CSP_REPORT_ONLY was False, so this is enforced; use
# CONTENT_SECURITY_POLICY_REPORT_ONLY to trial changes without blocking.
CONTENT_SECURITY_POLICY = {
    "DIRECTIVES": {
        "default-src": ["'self'"],
        "script-src": [
            "'self'",
            "'unsafe-inline'",              # Required: inline scripts and event handlers
            "https://3dmol.org",
            "https://unpkg.com",            # NGL.js 3D viewer in sequenceForm.html
            "https://cdn.plot.ly",          # Plotly.js charts in details view
            "https://kit.fontawesome.com",  # Font Awesome Kit loader
        ],
        "style-src": [
            "'self'",
            "'unsafe-inline'",              # Required: inline style= attributes throughout templates
            "https://cdnjs.cloudflare.com", # Font Awesome in base.html + sequenceForm.html
            "https://fonts.googleapis.com", # Google Fonts CSS (Inter font)
            "https://ka-f.fontawesome.com", # Font Awesome Kit dynamic CSS
        ],
        "font-src": [
            "'self'",
            "https://cdnjs.cloudflare.com", # Font Awesome webfonts (.woff2)
            "https://fonts.gstatic.com",    # Google Fonts woff2 files (Inter font)
            "https://ka-f.fontawesome.com", # Font Awesome Kit webfonts
        ],
        "img-src": [
            "'self'",
            "data:",                        # SVG/PNG plots served as data URIs in detail views
            "https://upload.wikimedia.org", # Wikipedia species thumbnails
        ],
        "connect-src": [
            "'self'",
            "https://ka-f.fontawesome.com", # Font Awesome Kit fetch
            "https://alphafold.ebi.ac.uk",  # AlphaFold CIF structure files for 3D viewer
        ],
        "frame-ancestors": ["'none'"],      # No page embeds this site via <iframe>
        "object-src": ["'none'"],           # No Flash/plugins
        "base-uri": ["'self'"],             # Prevents base-tag injection attacks
    },
}

# Permissions Policy (django-permissions-policy 4.x)
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
    }
}

PERMISSIONS_POLICY = {
    "camera": [],
    "microphone": [],
    "geolocation": [],
    "payment": [],
    "usb": [],
    "fullscreen": ("self",),        # NGL 3D viewer uses the Fullscreen API
    "clipboard-write": ("self",),   # sequenceForm uses navigator.clipboard.writeText()
}

#############################################################
# Logging
# Writes to a file regardless of DEBUG, so warnings/exceptions logged from
# application code are visible in production without needing DEBUG=True
# (Django's default console handler only fires when DEBUG=True, and no
# ADMINS/EMAIL_BACKEND is configured for mail_admins to have any effect).

LOG_DIR = BASE_DIR / 'logs'
os.makedirs(LOG_DIR, exist_ok=True)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{asctime} {levelname} {name} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'file': {
            'level': 'WARNING',
            'class': 'logging.FileHandler',
            'filename': LOG_DIR / 'django.log',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'apps': {
            'handlers': ['file'],
            'level': 'WARNING',
            'propagate': True,
        },
    },
}