"""
Django settings for traceyDB project.

Generated by 'django-admin startproject' using Django 3.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""
import os, environ
from pathlib import Path
import mimetypes

mimetypes.add_type("text/css", ".css", True)

env = environ.Env(
    # set casting, default value
    DEBUG=(bool, True)
)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
CORE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Take environment variables from .env file
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY', default='S#perS3crEt_007')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env('DEBUG')

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Assets Management
ASSETS_ROOT = os.getenv('ASSETS_ROOT', '/static/assets')

ALLOWED_HOSTS        = ['dcsrs-tracey.ad.unil.ch', 'tracey.unil.ch', 'localhost', 'localhost:85', '127.0.0.1', env('SERVER', default='127.0.0.1') ]
CSRF_TRUSTED_ORIGINS = ['http://localhost:85', 'http://127.0.0.1', 'https://' + env('SERVER', default='127.0.0.1') ]

# Captcha options
CAPTCHA_CHALLENGE_FUNCT = 'captcha.helpers.math_challenge' # default: 'captcha.helpers.random_char_challenge'
CAPTCHA_LETTER_ROTATION = (-20, 20)
CAPTCHA_NOISE_FUNCTIONS = ('captcha.helpers.noise_arcs','captcha.helpers.noise_dots',)
CAPTCHA_FONT_SIZE = 30
#CAPTCHA_2X_IMAGE = True # this makes the image slightly more readable on e.g. HiDPI screens, but could also make the CAPTCHA potentially easier to break by a bot.

# example of function for captcha
# def random_digit_challenge():
#     ret = u''
#     for i in range(6):
#         ret += str(random.randint(0,9))
#     return ret, ret


# Max GET/POST fields
DATA_UPLOAD_MAX_NUMBER_FIELDS = 20000

# Application definition
INSTALLED_APPS = [
    'apps.config.AppsConfig',
    'captcha',
    'django_extensions',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_htmx',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_htmx.middleware.HtmxMiddleware',
    'csp.middleware.CSPMiddleware',
    'django_permissions_policy.PermissionsPolicyMiddleware',
]

ROOT_URLCONF = 'core.urls'
LOGIN_REDIRECT_URL = "home"  # Route defined in home/urls.py
LOGOUT_REDIRECT_URL = "home"  # Route defined in home/urls.py
TEMPLATE_DIR = os.path.join(CORE_DIR, "apps/templates")  # ROOT dir for templates

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [TEMPLATE_DIR],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'apps.context_processors.cfg_assets_root',
            ],
            'libraries':{
                'template_filters': 'apps.templatetags.template_filters',
            },
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'tracey',
        'USER': 'tracey',
        'PASSWORD': 'tracey',
        'HOST': 'localhost',
        'PORT': '3306',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 8,
        }
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Europe/Zurich'

USE_I18N = True

USE_L10N = True

USE_TZ = True


#############################################################
# SRC: https://devcenter.heroku.com/articles/django-assets

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.9/howto/static-files/
STATIC_ROOT = os.path.join(CORE_DIR, 'staticfiles')
STATIC_URL = '/static/'

# Extra places for collectstatic to find static files.
STATICFILES_DIRS = (
    os.path.join(CORE_DIR, 'apps/static'),
)


#############################################################
#############################################################

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


#############################################################

# Content Security Policy (django-csp 3.8)
CSP_REPORT_ONLY = False  # Enforced — set to True only for debugging

CSP_DEFAULT_SRC = ("'self'",)

CSP_SCRIPT_SRC = (
    "'self'",
    "'unsafe-inline'",              # Required: <script> blocks in templates have no nonces
    "https://3dmol.org",
    "https://unpkg.com",            # NGL.js 3D viewer in sequenceForm.html
    "https://cdn.plot.ly",          # Plotly.js charts in details view
    "https://kit.fontawesome.com",  # Font Awesome Kit loader
)

CSP_STYLE_SRC = (
    "'self'",
    "'unsafe-inline'",              # Required: inline style= attributes throughout templates
    "https://cdnjs.cloudflare.com", # Font Awesome in sequenceForm.html + base-fullscreen.html
    "https://fonts.googleapis.com", # Google Fonts CSS (Inter font)
    "https://ka-f.fontawesome.com", # Font Awesome Kit dynamic CSS
)

CSP_FONT_SRC = (
    "'self'",
    "https://cdnjs.cloudflare.com", # Font Awesome webfonts (.woff2)
    "https://fonts.gstatic.com",    # Google Fonts woff2 files (Inter font)
    "https://ka-f.fontawesome.com", # Font Awesome Kit webfonts
)

CSP_IMG_SRC = (
    "'self'",
    "data:",                        # SVG/PNG plots served as data URIs in detail views
)

CSP_CONNECT_SRC = (
    "'self'",
    "https://ka-f.fontawesome.com", # Font Awesome Kit fetch
    "https://alphafold.ebi.ac.uk",  # AlphaFold CIF structure files for 3D viewer
)

CSP_FRAME_ANCESTORS = ("'none'",)   # No page embeds this site via <iframe>

CSP_OBJECT_SRC = ("'none'",)        # No Flash/plugins

CSP_BASE_URI = ("'self'",)          # Prevents base-tag injection attacks

# Permissions Policy (django-permissions-policy 4.x)
PERMISSIONS_POLICY = {
    "camera": [],
    "microphone": [],
    "geolocation": [],
    "payment": [],
    "usb": [],
    "fullscreen": ("self",),        # NGL 3D viewer uses the Fullscreen API
    "clipboard-write": ("self",),   # sequenceForm uses navigator.clipboard.writeText()
}