# Generated by Django 3.2.5 on 2022-07-04 14:43

from django.db import migrations, models
from django.conf import settings

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analysislevels',
            fields=[
                ('analysislevel_id', models.AutoField(db_column='analysisLevel_id', primary_key=True, serialize=False)),
                ('name', models.TextField(db_collation='latin1_swedish_ci')),
                ('comments', models.TextField(blank=True, db_collation='latin1_swedish_ci', null=True)),
                ('level', models.IntegerField(unique=True)),
            ],
            options={
                'db_table': 'analysislevels',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Associatedsequences',
            fields=[
                ('associatedsequence_id', models.AutoField(db_column='associatedSequence_id', primary_key=True, serialize=False)),
                ('gi', models.TextField(db_collation='latin1_swedish_ci')),
                ('shortname', models.CharField(db_collation='latin1_swedish_ci', max_length=50)),
                ('sequence', models.TextField(db_collation='latin1_swedish_ci')),
                ('active', models.IntegerField()),
                ('comments', models.TextField(blank=True, db_collation='latin1_swedish_ci', null=True)),
                ('multi_gi', models.TextField(blank=True, db_collation='latin1_swedish_ci', null=True)),
                ('sp', models.TextField(blank=True, db_collation='latin1_swedish_ci', null=True)),
                ('changelog', models.TextField(blank=True, db_collation='latin1_swedish_ci', db_column='changeLog', null=True)),
                ('private', models.PositiveIntegerField()),
                ('aliases', models.TextField(blank=True, db_collation='latin1_swedish_ci', null=True)),
                ('proteinlayoutgroup_id', models.IntegerField(blank=True, db_column='proteinLayoutGroup_id', null=True)),
            ],
            options={
                'db_table': 'associatedsequences',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Domainchild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domaingroupname', models.CharField(db_collation='utf8_general_ci', db_column='domainGroupName', max_length=50)),
                ('domaingroup_id', models.IntegerField(db_column='domainGroup_id')),
                ('motiflineage', models.CharField(blank=True, db_collation='utf8_general_ci', db_column='MotifLineage', max_length=50, null=True)),
                ('domaingroupparent_id', models.CharField(blank=True, db_collation='utf8_general_ci', db_column='domainGroupParent_id', max_length=100, null=True)),
                ('analysislevel', models.IntegerField(db_column='analysisLevel')),
            ],
            options={
                'db_table': 'domainchild',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Domaingroups',
            fields=[
                ('domaingroup_id', models.AutoField(db_column='domainGroup_id', primary_key=True, serialize=False)),
                ('domaingroupname', models.CharField(db_column='domainGroupName', max_length=50)),
                ('domaingroupfunctionalname', models.CharField(blank=True, db_column='domainGroupFunctionalName', max_length=50, null=True)),
                ('domaingroupshortname', models.TextField(blank=True, db_column='domainGroupShortname', null=True)),
                ('domaingroupcomments', models.TextField(blank=True, db_column='domainGroupComments', null=True)),
                ('domaingroupparent_id', models.CharField(blank=True, db_column='domainGroupParent_id', max_length=100, null=True)),
                ('domaingrouplength', models.IntegerField(db_column='domainGroupLength')),
                ('analysislevel', models.IntegerField(db_column='analysisLevel')),
                ('appendixname', models.TextField(blank=True, db_column='appendixName', null=True)),
                ('mappingstring', models.TextField(db_column='mappingString')),
                ('softcutoff', models.FloatField(db_column='softCutoff')),
                ('strictcutoff', models.FloatField(db_column='strictCutoff')),
                ('domaingroupmodel_id', models.IntegerField(blank=True, db_column='domainGroupModel_id', null=True)),
                ('isalignable', models.IntegerField(blank=True, db_column='isAlignable', null=True)),
            ],
            options={
                'db_table': 'domaingroups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Domains',
            fields=[
                ('domain_id', models.AutoField(primary_key=True, serialize=False)),
                ('domainname', models.CharField(db_column='domainName', max_length=50)),
                ('domaincomments', models.TextField(blank=True, db_column='domainComments', null=True)),
                ('alignment', models.TextField()),
                ('alignmentlength', models.IntegerField(db_column='alignmentLength')),
            ],
            options={
                'db_table': 'domains',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Falsepositives',
            fields=[
                ('falsepositive_id', models.AutoField(db_column='falsePositive_id', primary_key=True, serialize=False)),
                ('domain_id', models.PositiveIntegerField()),
                ('gi', models.TextField()),
            ],
            options={
                'db_table': 'falsepositives',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Genes',
            fields=[
                ('gene_id', models.AutoField(primary_key=True, serialize=False)),
                ('ncbigene_id', models.CharField(db_column='ncbiGene_id', max_length=10)),
            ],
            options={
                'db_table': 'genes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Genomesource',
            fields=[
                ('genomesource_id', models.AutoField(db_column='genomeSource_id', primary_key=True, serialize=False)),
                ('ftplink', models.TextField(blank=True, db_column='ftpLink', null=True)),
                ('wwwlink', models.TextField(blank=True, db_column='wwwLink', null=True)),
                ('sequencetype', models.TextField(db_column='sequenceType')),
                ('version', models.TextField()),
                ('timecreated', models.DateTimeField(db_column='timeCreated')),
                ('timelastmodified', models.DateTimeField(db_column='timeLastModified')),
                ('xmlparameter', models.TextField(db_column='xmlParameter')),
                ('sourcedatabase', models.TextField(db_column='sourceDatabase')),
            ],
            options={
                'db_table': 'genomesource',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Goldstatus',
            fields=[
                ('goldstamp', models.CharField(db_column='goldStamp', max_length=10, primary_key=True, serialize=False)),
                ('ncbi_taxonomy_id', models.IntegerField()),
                ('projectstatus', models.CharField(max_length=25)),
                ('sequencingstatus', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'goldstatus',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Inserterrors',
            fields=[
                ('inserterror_id', models.AutoField(db_column='insertError_id', primary_key=True, serialize=False)),
                ('startposition', models.IntegerField()),
                ('stopposition', models.IntegerField()),
            ],
            options={
                'db_table': 'inserterrors',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Layouts',
            fields=[
                ('layout_id', models.AutoField(primary_key=True, serialize=False)),
                ('layoutcomments', models.TextField(blank=True, db_column='layoutComments', null=True)),
                ('layoutrank', models.IntegerField(db_column='layoutRank')),
                ('layoutstatus', models.TextField(db_column='layoutStatus')),
                ('layoutstring', models.TextField(db_column='layoutString')),
            ],
            options={
                'db_table': 'layouts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Methods',
            fields=[
                ('method_id', models.AutoField(primary_key=True, serialize=False)),
                ('domaingroup_id', models.IntegerField(db_column='domainGroup_id')),
                ('input', models.TextField(blank=True, null=True)),
                ('type', models.TextField()),
                ('parameter', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'methods',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Motifs',
            fields=[
                ('motifname', models.TextField(db_collation='latin1_swedish_ci')),
                ('startposition', models.IntegerField()),
                ('stopposition', models.IntegerField()),
                ('motifcomments', models.TextField(blank=True, db_collation='latin1_swedish_ci', db_column='motifComments', null=True)),
                ('motif_id', models.AutoField(primary_key=True, serialize=False)),
                ('gaps', models.TextField(blank=True, db_collation='latin1_swedish_ci', null=True)),
                ('active', models.IntegerField()),
                ('motifrank', models.IntegerField(blank=True, db_column='motifRank', null=True)),
                ('asciioutput', models.TextField(blank=True, db_collation='latin1_swedish_ci', db_column='asciiOutput', null=True)),
                ('binaryoutput', models.TextField(blank=True, db_column='binaryOutput', null=True)),
            ],
            options={
                'db_table': 'motifs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NcbiTaxonomy',
            fields=[
                ('rank', models.TextField(db_collation='latin1_swedish_ci')),
                ('scientificname', models.TextField(db_collation='latin1_swedish_ci', db_column='scientificName')),
                ('division', models.TextField(db_collation='latin1_swedish_ci')),
                ('commonname', models.TextField(db_collation='latin1_swedish_ci', db_column='commonName')),
                ('genus', models.TextField(db_collation='latin1_swedish_ci')),
                ('species', models.TextField(db_collation='latin1_swedish_ci')),
                ('subspecies', models.TextField(db_collation='latin1_swedish_ci')),
                ('ncbi_taxonomy_id', models.IntegerField(db_column='ncbi_Taxonomy_id', primary_key=True, serialize=False)),
                ('nucnumber', models.IntegerField(blank=True, db_column='nucNumber', null=True)),
                ('estnumber', models.IntegerField(blank=True, db_column='estNumber', null=True)),
                ('protnumber', models.IntegerField(db_column='protNumber')),
                ('structnumber', models.IntegerField(blank=True, db_column='structNumber', null=True)),
                ('genomenumber', models.IntegerField(blank=True, db_column='genomeNumber', null=True)),
                ('genenumber', models.IntegerField(blank=True, db_column='geneNumber', null=True)),
                ('active', models.IntegerField()),
                ('lastupdate', models.DateField(blank=True, db_column='lastUpdate', null=True)),
                ('class_field', models.TextField(blank=True, db_collation='latin1_swedish_ci', db_column='class', null=True)),
                ('parent_id', models.IntegerField()),
            ],
            options={
                'db_table': 'ncbi_taxonomy',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NcbiTaxonomysynonyms',
            fields=[
                ('name', models.TextField()),
                ('ncbi_taxonomysynonyms_id', models.AutoField(db_column='NCBI_TaxonomySynonyms_id', primary_key=True, serialize=False)),
                ('class_field', models.TextField(blank=True, db_column='class', null=True)),
            ],
            options={
                'db_table': 'ncbi_taxonomysynonyms',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='P2Dmapping',
            fields=[
                ('p2dmapping_id', models.AutoField(db_column='p2dMapping_id', primary_key=True, serialize=False)),
                ('position', models.IntegerField()),
            ],
            options={
                'db_table': 'p2dmapping',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PollsChoice',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('choice_text', models.CharField(max_length=200)),
                ('votes', models.IntegerField()),
            ],
            options={
                'db_table': 'polls_choice',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PollsQuestion',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('question_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'polls_question',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Proteinlayoutgroups',
            fields=[
                ('proteinlayoutgroup_id', models.AutoField(db_column='proteinLayoutGroup_id', primary_key=True, serialize=False)),
                ('proteinlayoutgroupname', models.CharField(db_column='proteinLayoutGroupName', max_length=50)),
                ('proteinlayoutgroupfunctionalname', models.CharField(blank=True, db_column='proteinLayoutGroupFunctionalName', max_length=50, null=True)),
                ('proteinlayoutgroupshortname', models.TextField(blank=True, db_column='proteinLayoutGroupShortname', null=True)),
                ('proteinlayoutgroupcomments', models.TextField(blank=True, db_column='proteinLayoutGroupComments', null=True)),
                ('proteinlayoutgroupparent_id', models.IntegerField(blank=True, db_column='proteinLayoutGroupParent_id', null=True)),
                ('proteinlayoutgrouplength', models.IntegerField(db_column='proteinLayoutGroupLength')),
                ('analysislevel', models.IntegerField(db_column='analysisLevel')),
                ('appendixname', models.TextField(blank=True, db_column='appendixName', null=True)),
                ('mappingstring', models.TextField(db_column='mappingString')),
            ],
            options={
                'db_table': 'proteinlayoutgroups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Proteinlayouts',
            fields=[
                ('proteinlayout_id', models.AutoField(db_column='proteinLayout_id', primary_key=True, serialize=False)),
                ('proteinlayoutname', models.CharField(db_column='proteinLayoutName', max_length=50)),
                ('proteinlayoutcomments', models.TextField(blank=True, db_column='proteinLayoutComments', null=True)),
                ('layout', models.TextField()),
                ('layoutlength', models.IntegerField(db_column='layoutLength')),
            ],
            options={
                'db_table': 'proteinlayouts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Secondarydomainstructures',
            fields=[
                ('secondarydomainstructure_id', models.AutoField(db_column='secondaryDomainStructure_id', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('comments', models.TextField(blank=True, null=True)),
                ('dssp', models.TextField()),
                ('domaingroup_id', models.IntegerField(db_column='domainGroup_id')),
            ],
            options={
                'db_table': 'secondarydomainstructures',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Secondaryproteinlayouts',
            fields=[
                ('secondaryproteinlayout_id', models.AutoField(db_column='secondaryProteinLayout_id', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('comments', models.TextField(blank=True, null=True)),
                ('dssp', models.TextField()),
                ('proteinlayoutgroup_id', models.IntegerField(db_column='proteinLayoutGroup_id')),
            ],
            options={
                'db_table': 'secondaryproteinlayouts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sequences',
            fields=[
                ('sequence_id', models.AutoField(primary_key=True, serialize=False)),
                ('foreignannotation', models.TextField(db_collation='latin1_swedish_ci', db_column='foreignAnnotation')),
                ('sequenceshortname', models.CharField(db_collation='latin1_swedish_ci', db_column='sequenceShortname', max_length=50)),
                ('annotation', models.TextField(db_collation='latin1_swedish_ci')),
                ('sequence', models.TextField(db_collation='latin1_swedish_ci')),
                ('sequencestatus', models.TextField(blank=True, db_collation='latin1_swedish_ci', db_column='sequenceStatus', null=True)),
                ('sequencecomments', models.TextField(blank=True, db_collation='latin1_swedish_ci', db_column='sequenceComments', null=True)),
                ('dbxref', models.CharField(max_length=25)),
                ('changelog', models.TextField(blank=True, db_collation='latin1_swedish_ci', db_column='changeLog', null=True)),
                ('private', models.PositiveIntegerField()),
                ('aliases', models.TextField(blank=True, db_collation='latin1_swedish_ci', null=True)),
                ('sourcedatabase', models.TextField(db_collation='latin1_swedish_ci', db_column='sourceDatabase')),
                ('replacedby', models.IntegerField(db_column='replacedBy')),
                ('sequencetype', models.CharField(db_collation='latin1_swedish_ci', db_column='sequenceType', max_length=25)),
            ],
            options={
                'db_table': 'sequences',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('species_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('comments', models.TextField(blank=True, null=True)),
                ('parent_id', models.IntegerField(blank=True, null=True)),
                ('taxonomy_id', models.PositiveIntegerField()),
                ('shortname', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'species',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Synonymgroups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id1', models.IntegerField()),
                ('id2', models.IntegerField()),
                ('comments', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'synonymgroups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Taxonomies',
            fields=[
                ('taxonomy_id', models.AutoField(primary_key=True, serialize=False)),
                ('commonname', models.TextField(blank=True, db_collation='latin1_swedish_ci', db_column='commonName', null=True)),
                ('scientificname', models.TextField(blank=True, db_collation='latin1_swedish_ci', db_column='scientificName', null=True)),
                ('taxonomycomments', models.TextField(blank=True, db_collation='latin1_swedish_ci', db_column='taxonomyComments', null=True)),
                ('taxonomyparent_id', models.IntegerField(db_column='taxonomyParent_id')),
                ('analysislevel', models.CharField(db_collation='latin1_swedish_ci', db_column='analysisLevel', max_length=15)),
                ('taxonomyrank', models.TextField(blank=True, db_collation='latin1_swedish_ci', db_column='taxonomyRank', null=True)),
                ('taxonomyshortname', models.TextField(db_collation='latin1_swedish_ci', db_column='taxonomyShortname')),
                ('ncbi_taxonomy_id', models.IntegerField(db_column='ncbi_Taxonomy_id')),
                ('taxonomystatus', models.TextField(db_collation='latin1_swedish_ci', db_column='taxonomyStatus')),
            ],
            options={
                'db_table': 'taxonomies',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tertiarydomainstructures',
            fields=[
                ('tertiarydomainstructure_id', models.AutoField(db_column='tertiaryDomainStructure_id', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('comments', models.TextField()),
                ('pdb', models.TextField()),
                ('domaingroup_id', models.IntegerField(blank=True, db_column='domainGroup_id', null=True)),
            ],
            options={
                'db_table': 'tertiarydomainstructures',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tertiaryproteinlayouts',
            fields=[
                ('tertiaryproteinlayout_id', models.AutoField(db_column='tertiaryProteinLayout_id', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('comments', models.TextField(blank=True, null=True)),
                ('pdb', models.TextField()),
                ('proteinlayoutgroup_id', models.IntegerField(db_column='proteinLayoutGroup_id')),
            ],
            options={
                'db_table': 'tertiaryproteinlayouts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Updatetask2Sequences',
            fields=[
                ('updatetask2sequences_id', models.AutoField(db_column='updateTask2sequences_id', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'updatetask2sequences',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Updatetask2User',
            fields=[
                ('updatetask2user_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'updatetask2user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Updatetasks',
            fields=[
                ('updatetask_id', models.AutoField(db_column='updateTask_id', primary_key=True, serialize=False)),
                ('updatetasktype', models.CharField(db_column='updateTaskType', max_length=25)),
                ('affectedtable', models.CharField(db_column='affectedTable', max_length=25)),
                ('updatetaskcomments', models.BigIntegerField(blank=True, db_column='updateTaskComments', null=True)),
                ('taskupdatetime', models.DateTimeField(db_column='taskUpdateTime')),
            ],
            options={
                'db_table': 'updatetasks',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=60)),
                ('password', models.CharField(max_length=60)),
                ('rights', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Verifylayouts',
            fields=[
                ('verifylayout_id', models.AutoField(db_column='verifyLayout_id', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'verifylayouts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Verifymotifs',
            fields=[
                ('motifname', models.TextField(db_collation='latin1_swedish_ci')),
                ('startposition', models.IntegerField()),
                ('stopposition', models.IntegerField()),
                ('verifymotifcomments', models.TextField(blank=True, db_collation='latin1_swedish_ci', db_column='verifyMotifComments', null=True)),
                ('verifymotif_id', models.AutoField(db_column='verifyMotif_id', primary_key=True, serialize=False)),
                ('gaps', models.TextField(blank=True, db_collation='latin1_swedish_ci', null=True)),
                ('active', models.IntegerField()),
                ('verifymotifrank', models.IntegerField(blank=True, db_column='verifyMotifRank', null=True)),
                ('asciioutput', models.TextField(blank=True, db_collation='latin1_swedish_ci', db_column='asciiOutput', null=True)),
                ('binaryoutput', models.TextField(blank=True, db_column='binaryOutput', null=True)),
            ],
            options={
                'db_table': 'verifymotifs',
                'managed': False,
            },
        ),
    ]
